# hosts++ 配置文件
version: "1.0"

# 基本服务器配置
port-type: http  # 可选: http, socks4, socks5, mixed
port: 7769  # 服务器监听端口
allow-lan: false  # 是否允许局域网访问

# 日志配置
log:
  level: info  # 日志级别: debug, info, warning, error
  output: console  # 输出方式: console, file, both, none
  file: ./logs/latest.log  # 日志文件路径
  timezone: Local  # 时区设置，使用 IANA 时区名称
  archive: true  # 是否启用日志归档
  compress: true  # 是否压缩归档的日志

# DNS 配置
dns:
  enable: true  # 是否启用自定义 DNS
  nameserver:
    - 'https://1.1.1.1/dns-query'
    - 'https://dns.google/dns-query'
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'

# 代理配置
proxy:
  use-system-proxy: true  # 是否使用系统代理
  enable: false  # 是否启用自定义代理
  server: 127.0.0.1:7890  # 代理服务器地址
  username: ""  # 代理认证用户名（如需）
  password: ""  # 代理认证密码（如需）
  type: http  # 代理类型: http, socks4, socks5

  # 不使用代理的地址列表
  bypass:
    - localhost
    - 127.0.0.0/8
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - ::1
    - fe80::/10

# 缓存配置
cache:
  dns: true  # 是否缓存 DNS 查询结果
  proxy-rules: true  # 是否缓存代理规则

# 规则集配置
rulesets:
  - name: "openai-redirect"
    rules:
      - type: single-to-single
        from: "www.google.com"
        to: "www.baidu.com"

      - type: single-to-single
        from: "www.google.com:443"
        to: "www.baidu.com:443"

      - type: multi-to-single
        from: "chat.openai.com,platform.openai.com"
        to: openai.myproxy.com

      - type: multi-to-multi
        from: "^(.+)\\.openai\\.com$"
        to: "\\$1.openaiproxy.com"
        regex: true

  - name: "google-services"
    rules:
      - type: multi-to-multi
        from: "^(.+)\\.google\\.com$"
        to: "\\$1.google.com.hk"
        regex: true

# CA 证书配置
ca:
  cert-path: "./ca.pem"
  key-path: "./ca.key"
  valid-for: 87600h  # 10 年
  subject:
    organization:
      - "hosts++ Proxy"
    organizational-unit:
      - "Created by wisdgod"
    common-name: "DO_NOT_TRUST_hosts++Root"

# 高级选项
advanced:
  connection-timeout: 30s
  idle-timeout: 300s
  max-connections: 1000
  buffer-size: 4096
  tls-handshake-timeout: 10s
