listen_addr: ":8080"
log_level: "debug"
use_system_hosts: true
dns_cache_duration: "5m"
parent_proxy: "http://127.0.0.1:2080"
verify_server_cert: true
copy_real_cert_status: true
rules:
  example_rule:
    type: "single-to-single"
    enabled: true
    fake_hosts: ["example.com:443"]
    real_hosts: ["www.google.com:443"]
    proxy_websocket: true
  testc_rule:
    type: "single-to-single"
    enabled: true
    fake_hosts: ["api.openai.com:443"]
    real_hosts: ["my-api.wisdgod.com:443"]
    proxy_websocket: true
  test_rule:
    type: "single-to-single"
    enabled: true
    fake_hosts: ["termux.com:443"]
    real_hosts: ["t.987452.xyz:443"]
    headers:
      request:
        "Origin": "https://t.987452.xyz"
        "Referer": "https://t.987452.xyz/"
    proxy_websocket: true
  multi_to_single_rule:
    type: "multi-to-single"
    enabled: true
    fake_hosts: ["example1.com:443", "example2.com:443"]
    real_hosts: ["www.bing.com:443"]
    proxy_websocket: false
  single_to_multi_rule:
    type: "single-to-multi"
    enabled: true
    fake_hosts: ["example3.com:443"]
    real_hosts: ["www.google.com:443", "www.bing.com:443", "www.yahoo.com:443"]
    proxy_websocket: true
  regex_rule:
    type: "multi-to-multi"
    enabled: true
    pattern: "^(.+)\\.example\\.com:443$"
    replacement: "${1}.google.com:443"
    proxy_websocket: true
    headers:
      request:
        "Origin": ""
        "Referer": ""
